### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by nkbt** [jhusain/eslint-plugin-immutable#1]
First of all, thanks for the great idea and such a simple implementation!

But...

``` sh
08:09 $ npm install eslint-plugin-immutable --save-dev
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/nkbt/.nvm/versions/node/v5.7.1/bin/node" "/Users/nkbt/.nvm/versions/node/v5.7.1/bin/npm" "install" "eslint-plugin-immutable" "--save-dev"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/eslint-plugin-immutable
npm ERR! 404 
npm ERR! 404  'eslint-plugin-immutable' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nkbt/mh/atlas-ui/npm-debug.log
✘
```

Immutability FTW \o/

**Comment by alexhawkins** [comment]
+1

**Comment by khalillechelt** [comment]
Hi @jhusain & @cerealbox do you guys plan on publishing this on npm?

If you are too busy I am happy to do it for you.

**Comment by jhusain** [comment]
Sorry, my father has been in town and I've just been traveling around. Go ahead and publish if you like.

JH

**Comment by khalillechelt** [comment]
Ah, it looks like somebody else did that already :smile: 

https://www.npmjs.com/package/eslint-plugin-immutable

**Comment by SteveALee** [comment]
npm module works like a dream - thanks. Now have fully immutable cyclejs code. 

Better approach that using DeepFreeze in unit tests.

**Comment by khalillechelt** [comment]
yeah it's a great solution!

**Comment by nkbt** [comment]
Closing since it is published already.
