### ISSUE TITLE
Not allow mutate `window` object but need

### ISSUE THREAD

**Issue by JimmyLv** [jhusain/eslint-plugin-immutable#17]
```
const store = window.store = createStore(...)
```

**Comment by ljharb** [comment]
Why would you want to create a global?

**Comment by JimmyLv** [comment]
@ljharb aha, actually just want to use `store` in devtool console easily.

**Comment by ljharb** [comment]
@JimmyLv eslint rules don't need to apply to dev. plus, what about a debugger breakpoint?

**Comment by JimmyLv** [comment]
@ljharb Aha, you are correct that we don't need use ESLint in dev.

Thank you very much, I would like to close this issue.
